### ISSUE TITLE
[FEATURE] Request a common block

### ISSUE THREAD

**Issue by suhuide** [MarkDing/Silabs-IoT-Quickstart#3]
**Is your feature request related to a problem? If so, please describe.**
All product line may need to introduce something in common, like Simplicity Studio, like how to setup a project.

**Describe the new feature you'd like**
Add a common block,provide some common knowledge, specific product block just provide a link.

@Jim-tech

**Comment by Jim-tech** [comment]
> **Is your feature request related to a problem? If so, please describe.**
> All product line may need to introduce something in common, like Simplicity Studio, like how to setup a project.
> 
> **Describe the new feature you'd like**
> Add a common block,provide some common knowledge, specific product block just provide a link.
> 
> @Jim-tech

Thanks for the suggestions.  I changed the WiKi structure a little bit, could you please take a look at it? @suhuide

**Comment by suhuide** [comment]
You did better than I wanted,thanks!

**Comment by MarkDing** [comment]
The platform and tool looks good to me for maintaining the common block. You can close the issue. @Jim-tech
